//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskQuestionProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AskQuestionDBEntities : DbContext
    {
        public AskQuestionDBEntities()
            : base("name=AskQuestionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerTable> AnswerTable { get; set; }
        public virtual DbSet<QuestionTable> QuestionTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
